### PR TITLE
fix remaining language names improperly split

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
@notconfusing ping

**Comment by waldyrious** [comment]
@notconfusing ping

**Comment by notconfusing** [comment]
@waldyrious thanks for the PR. Sorry it took me so long to merge. What are you drying to do by the way?

**Comment by waldyrious** [comment]
I honestly don't remember any more 😞 I just pinged because in one of my github/local repos cleanup rounds I came across this old PR of mine that had been lingering around. I probably achieved the goal I needed this for back when I first sent this PR, because otherwise I'd have notes somewhere about what was yet to be done.

**Pull request merged**
